# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgis
  database: unearthed_development
  host: localhost

test:
  adapter: postgis
  database: unearthed_test
  host: localhost

production:
  adapter: postgis
  database: unearthed_production
  host: localhost