# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: unearthed_development
  host: localhost

test:
  adapter: postgresql
  database: unearthed_test
  host: localhost

production:
  adapter: postgresql
  database: unearthed_production
  host: localhost
  # url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>